### ISSUE TITLE
Page design

### ISSUE THREAD

**Issue by Baptiste-J** [Biophotonics-Tyndall/GEN-TissueOpticsApp#1]
@jsmatias: I think most of the code for the app is finished. Now we need to design the pages to make them user friendly. I have a suggestion of design (I also put this in the repo under pageDesignIdea.png): 
![pageDesignIdea](https://user-images.githubusercontent.com/67267548/120867961-e864a200-c58a-11eb-8a38-9d218f8113ee.png)

Let me know if you think something like this is possible!

Cheers.

**Comment by Baptiste-J** [comment]
I like the new layout :-) There is one minor change that we can add. It would be good to have the wavelength selector always visible, that way we can see the changes when selecting a new wavelength. Currently, to update the wavelength of the top graph, you need to scroll down, change the wavelength and go back up. Do you think it would be possible to anchor the display options so that they don't move, and only the graph moves? 

I also remove the update button. I put it because on my first try of auto-updating the graphs when changing the content of the textboxes, the graph were update at each single keystroke which was a bit annoying. Not sur how you sorted this, but it's better now haha

**Comment by jsmatias** [comment]
> I like the new layout :-) There is one minor change that we can add. It would be good to have the wavelength selector always visible, that way we can see the changes when selecting a new wavelength. Currently, to update the wavelength of the top graph, you need to scroll down, change the wavelength and go back up. Do you think it would be possible to anchor the display options so that they don't move, and only the graph moves?
> 
Yes, it is possible. That was my initial intention as well, but it required a bit more work on that, and I wanted to share the current layout before moving forward. 
So, the feature is on the list for next action.

**Comment by Baptiste-J** [comment]
When I implemented the new layout in the first page with the table of the 3 different tissues, the table was super wide and as a result the chart area was quite small. I managed to reduce the size of the text field, but I entered their size one by one manually in the html file. Is it possible to have this in the CSS with one number that control everything?

**Comment by Baptiste-J** [comment]
I managed to reduce the size of the table by editing the CSS file and changing the padding value in the ".styled-table th" and ".styled-table td".

**Comment by jsmatias** [comment]
> I managed to reduce the size of the table by editing the CSS file and changing the padding value in the ".styled-table th" and ".styled-table td".

The size attribute for the ```<input>``` tag only works for the text type (at least on google chrome). I've changed the size of the input tags for the table with CSS and I increased again the padding as it was looking a bit squeezed on my small screen. lol
