### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by Baptiste-J** [Biophotonics-Tyndall/GEN-TissueOpticsApp#3]
@jsmatias Following Marcelo suggestion we can add an about page instead of the footer. I suggest to put the following info:

- A short description
- Credit to people developping the app
- Contact email (we can put mine)

**Comment by jsmatias** [comment]
I have created a formatted page with the headings for this info. Can you check if that makes sense, please? 
:)

**Comment by Baptiste-J** [comment]
Looks good! I started populatingthe page yesterday and added a licence (standard MTI software licence that is quite permissible). I will check with Stefan if people from Lund should be acknowledge and who.

**Comment by Baptiste-J** [comment]
I will add a section for the reviewers and help in the credit to add Marcelo and Jackie again
